<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>procexp</AssemblyName>
    <RootNamespace>Procexp.App</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <BuiltInComInteropSupport>false</BuiltInComInteropSupport>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Procexp.Model/Procexp.Model.csproj" />
    <ProjectReference Include="../Procexp.Sampling/Procexp.Sampling.csproj" />
    <ProjectReference Include="../Procexp.SystemStats/Procexp.SystemStats.csproj" />
    <ProjectReference Include="../Procexp.Net/Procexp.Net.csproj" />
    <ProjectReference Include="../Procexp.Provenance/Procexp.Provenance.csproj" />
    <ProjectReference Include="../Procexp.Autostart/Procexp.Autostart.csproj" />
    <ProjectReference Include="../Procexp.Actions/Procexp.Actions.csproj" />
    <ProjectReference Include="../Procexp.Gpu/Procexp.Gpu.csproj" />
    <ProjectReference Include="../Procexp.Privileged/Procexp.Privileged.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Procexp.App.Tests" />
  </ItemGroup>

</Project>
